### ISSUE TITLE
Before connect, if two messages are produced there is a channel ended error

### ISSUE THREAD

**Issue by PuKoren** [dial-once/node-bunnymq#17]
``` js
var amqp = require('bunnymq')().producer;

amqp.produce('queue:sample');
amqp.produce('queue:sample');
amqp.produce('queue:sample');
```

``` logs
gateway-screen-2 | 2016-02-25T11:33:20.833881800Z Potentially unhandled rejection [2] Error: Channel ended, no reply will be forthcoming
gateway-screen-2 | 2016-02-25T11:33:20.833909000Z     at rej (/usr/src/app/node_modules/amqplib/lib/channel.js:190:7)
gateway-screen-2 | 2016-02-25T11:33:20.833922100Z     at Channel.C._rejectPending (/usr/src/app/node_modules/amqplib/lib/channel.js:196:42)
gateway-screen-2 | 2016-02-25T11:33:20.833936100Z     at Channel.C.toClosed (/usr/src/app/node_modules/amqplib/lib/channel.js:160:8)
gateway-screen-2 | 2016-02-25T11:33:20.833946700Z     at Channel.C.accept (/usr/src/app/node_modules/amqplib/lib/channel.js:411:10)
gateway-screen-2 | 2016-02-25T11:33:20.833957300Z     at Connection.mainAccept [as accept] (/usr/src/app/node_modules/amqplib/lib/connection.js:63:33)
gateway-screen-2 | 2016-02-25T11:33:20.833968000Z     at Socket.go (/usr/src/app/node_modules/amqplib/lib/connection.js:476:48)
gateway-screen-2 | 2016-02-25T11:33:20.833978500Z     at emitNone (events.js:67:13)
gateway-screen-2 | 2016-02-25T11:33:20.833988900Z     at Socket.emit (events.js:166:7)
gateway-screen-2 | 2016-02-25T11:33:20.833999400Z     at emitReadable_ (_stream_readable.js:411:10)
gateway-screen-2 | 2016-02-25T11:33:20.834009900Z     at emitReadable (_stream_readable.js:405:7)
gateway-screen-2 | 2016-02-25T11:33:20.834020000Z     at readableAddChunk (_stream_readable.js:157:11)
gateway-screen-2 | 2016-02-25T11:33:20.834030500Z     at Socket.Readable.push (_stream_readable.js:110:10)
gateway-screen-2 | 2016-02-25T11:33:20.834041000Z     at TCP.onread (net.js:523:20)
```

**Comment by PuKoren** [comment]
Fixed on https://github.com/dial-once/node-bunnymq/commit/8077d6f9b03f6f76065826ccb7e1ea1e03237d12
